language: node_js
node_js:
  - "8"
  - "10"
addons:
    code_climate:
        repo_token: $supersecrettoken
env:
  matrix:
  - REACT=16.6
sudo: false

before_script:
  - npm install -g codeclimate-test-reporter

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info

