export const ACTION_TYPES = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  FETCH_ALL:"FETCH_ALL",
  ADD_ENTRY:"ADD_ENTRY",
  GET_ENTRY:"GET_ENTRY",
  EDIT_ENTRY:"EDIT_ENTRY",
  DELETE:"DELETE",
  NO_ENTRY:"NO_ENTRY"
};
